language: generic
sudo: required
script: swift build
matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: linux
      script: swift test
      services:
        - redis-server
      dist: trusty
      install:
        - wget https://swift.org/builds/swift-4.1.1-release/ubuntu1404/swift-4.1.1-RELEASE/swift-4.1.1-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-4.1.1-RELEASE-ubuntu14.04.tar.gz
        - export PATH=`pwd`/swift-4.1.1-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
